name: estamper
mode: emoji
format: "{emoji1}-{emoji2}-{word1}-{word2}-{date}-{user}@{commit}"

date:
  format: "yyyy-mm-dd-hh:mm:ss"
  timezone: "local"

words:
  allow:
    - silver
    - river
    - melon
    - orbit
    - pixel
    - debug
    - rocket
    - garden
    - banana
    - arcade

emojis:
  allow:
    - 🍉
    - 🛠️
    - 🚀
    - 🐶
    - 🍏
    - 🍌
    - 🧪
    - 🎮
    - ✨
    - 🧰

ascii:
  allow:
    - WM
    - TL
    - RX
    - DG
    - PX
    - QA
    - CI
    - GH
    - JS
    - OK

git:
  commitLength: 7
  includeBranch: true
  includeDirty: true
  usernameSource: github
  fallbackUsernameSource: git-config

badge:
  enabled: true
  position: bottom-right
  startVisible: true
  copyOnClick: true
  showDetailsOnClick: true
  theme: dark

output:
  json: "dist/estamper.json"
  js: "dist/estamper.js"
  htmlSnippet: "dist/estamper-snippet.html"
