export const defaultWords = [
  'silver',
  'golden',
  'crimson',
  'azure',
  'violet',
  'amber',
  'jade',
  'coral',
  'ivory',
  'slate',
  'river',
  'forest',
  'mountain',
  'ocean',
  'canyon',
  'valley',
  'island',
  'delta',
  'glacier',
  'melon',
  'mango',
  'cherry',
  'lemon',
  'peach',
  'plum',
  'grape',
  'orbit',
  'pixel',
  'vector',
  'debug',
  'patch',
  'build',
  'deploy',
  'branch',
  'matrix',
  'kernel',
  'socket',
  'buffer',
  'cipher',
  'proxy',
  'router',
  'rocket',
  'thunder',
  'signal',
  'echo',
  'mirror',
  'shadow',
  'phantom',
  'nova',
  'spark',
  'comet',
  'garden',
  'banana',
  'arcade',
];

export const defaultEmojis = [
  '🍉',
  '🍏',
  '🍌',
  '🍇',
  '🍊',
  '🍋',
  '🚀',
  '🛠️',
  '🐶',
  '🧪',
  '🎮',
  '✨',
  '🧰',
  '🌊',
  '🔥',
  '🎯',
  '💡',
  '🦊',
  '🐙',
  '🎸',
];

export const defaultAscii = ['WM', 'TL', 'RX', 'DG', 'PX', 'QA', 'CI', 'GH', 'OK', 'BG', 'FX', 'MG', 'VX', 'ZN'];

export const defaultFormat = '{env}-{cloud}-{token1}-{token2}-{word1}-{word2}-{date}-{time}-{user}@{commit}';
export const defaultFormatWithoutCloud = '{env}-{token1}-{token2}-{word1}-{word2}-{date}-{time}-{user}@{commit}';
export const asciiFormat = '{envAscii}-{cloudAscii}-{ascii1}-{ascii2}-{word1}-{word2}-{date}-{time}-{user}@{commit}';
export const asciiFormatWithoutCloud = '{envAscii}-{ascii1}-{ascii2}-{word1}-{word2}-{date}-{time}-{user}@{commit}';
